version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.0.0-alpha5
    ports:
      - "9200:9200"
    volumes:
      - local-folder:/usr/share/elasticsearch/data
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
  kibana:
    image: kibana:5.0.0-alpha5
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
